#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>
#include <HardwareSerial.h>

#define NUM_PULSADORES 6
#define NUM_RELES 2
#define NUM_EXPRESION 2
#define NUM_PERFILES 6

const int PINES_PULSADORES[NUM_PULSADORES] = {5, 6, 7, 15, 16, 3};
const int PINES_LEDS[NUM_PULSADORES] = {9, 10, 11, 12, 13, 46};
const int PINES_RELES[NUM_RELES] = {47, 48};
const int PINES_LEDS_RELES[NUM_RELES] = {20, 21};
const int PINES_EXPRESION[NUM_EXPRESION] = {1, 2};

const int PIN_MODO = 19;
const int PIN_PERFIL = 4;

#define TAM_PULSADORES    NUM_PULSADORES
#define TAM_CC_PULS       NUM_PULSADORES
#define TAM_MODO_PULS     NUM_PULSADORES
#define TAM_RELES         (NUM_PULSADORES * NUM_RELES)
#define TAM_CC_EXP        NUM_EXPRESION
#define TAM_PC_CERO       1
#define TAM_PERFIL (TAM_PULSADORES + TAM_CC_PULS + TAM_MODO_PULS + TAM_RELES + TAM_CC_EXP + TAM_PC_CERO)

#define OFF_PULSADORES 0
#define OFF_CC_PULS (OFF_PULSADORES + TAM_PULSADORES)
#define OFF_MODO_PULS (OFF_CC_PULS + TAM_CC_PULS)
#define OFF_RELES (OFF_MODO_PULS + TAM_MODO_PULS)
#define OFF_CC_EXP (OFF_RELES + TAM_RELES)
#define OFF_PC_CERO (OFF_CC_EXP + TAM_CC_EXP)

#define BASE_PERFIL(p) (p * TAM_PERFIL)

#define ADDR_PULSADORES(p) (BASE_PERFIL(p) + OFF_PULSADORES)
#define ADDR_CC_PULS(p) (BASE_PERFIL(p) + OFF_CC_PULS)
#define ADDR_MODO_PULS(p) (BASE_PERFIL(p) + OFF_MODO_PULS)
#define ADDR_RELES(p) (BASE_PERFIL(p) + OFF_RELES)
#define ADDR_CC_EXP(p) (BASE_PERFIL(p) + OFF_CC_EXP)
#define ADDR_PC_CERO(p) (BASE_PERFIL(p) + OFF_PC_CERO)

#define EEPROM_TOTAL (TAM_PERFIL * NUM_PERFILES)
#define ADDR_PERFIL_DEFECTO (EEPROM_TOTAL)

const uint8_t PERFIL_DEFECTO_PULSADORES[NUM_PERFILES][NUM_PULSADORES] =
{
    {1,2,3,4,5,6},
    {1,2,3,4,5,6},
    {1,2,3,4,5,6},
    {1,2,3,4,5,6},
    {1,2,3,4,5,6},
    {1,2,3,4,5,6}
};

const uint8_t PERFIL_DEFECTO_CC[NUM_PERFILES][NUM_PULSADORES] = { {0} };
const uint8_t PERFIL_DEFECTO_MODO[NUM_PERFILES][NUM_PULSADORES] = { {0} };
const uint8_t PERFIL_DEFECTO_RELES[NUM_PERFILES][NUM_PULSADORES][NUM_RELES] = {0};

const uint8_t PERFIL_DEFECTO_CC_EXP[NUM_PERFILES][NUM_EXPRESION] =
{
    {11,4},{11,4},{11,4},{11,4},{11,4},{11,4}
};

const uint8_t PERFIL_DEFECTO_PC_CERO[NUM_PERFILES] = {1,1,1,1,1,1};

HardwareSerial Serial_MIDI(1);

#define TXD_PIN 17
#define RXD_PIN 18

#define AP_SSID "Mapo MIDI Control"
#define AP_PASSWORD "12345678"
#define HOST_NAME "mapomidi"
#define mdns "mapomidi"

#endif
